name: "Continuous Integration"

on: [push]

jobs:
  run-tests:
    name: Run Application Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install test requirements
        run: pip install -r requirements-test.txt

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: make test
